<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg><img src=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2019-10-07T06:03:06Z" name="Suite" finished-at="2019-10-07T06:03:32Z" duration-ms="26155">
    <groups>
    </groups>
    <test started-at="2019-10-07T06:03:06Z" name="Test" finished-at="2019-10-07T06:03:32Z" duration-ms="26155">
      <class name="qa.automation.demo.testcases.Logintest">
        <test-method is-config="true" signature="setup()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:06Z" name="setup" finished-at="2019-10-07T06:03:15Z" duration-ms="9331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Signin()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:15Z" name="Signin" finished-at="2019-10-07T06:03:19Z" duration-ms="4073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signin -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:19Z" name="Teardown" finished-at="2019-10-07T06:03:19Z" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:19Z" name="setup" finished-at="2019-10-07T06:03:28Z" duration-ms="8441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyTitle()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:28Z" name="verifyTitle" finished-at="2019-10-07T06:03:31Z" duration-ms="2758" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [AUTHENTICATION] but found [AUTHENTICTION]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [AUTHENTICATION] but found [AUTHENTICTION]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at qa.automation.demo.testcases.Logintest.verifyTitle(Logintest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg><img src=verifyTitleMon_Oct_07_11_33_32_IST_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:qa.automation.demo.testcases.Logintest@38afe297]" started-at="2019-10-07T06:03:32Z" name="Teardown" finished-at="2019-10-07T06:03:32Z" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- qa.automation.demo.testcases.Logintest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
